guests = ['mama','papa','brat','devushka']
len(guests)
del_item = 'brat'
guests.remove(del_item)
len(guests)
guests.append('drug')
len(guests)
info = f"ya kupil noviy stol, tak chto pridet ewe 3 moih druga"
print(info)
guests.insert(2, 'drug1')
len(guests)
guests.insert(0, 'drug2')
len(guests)
guests.append('drug3')
len(guests)
invite = f"prihodite na moi obed na 14:00"
print(guests)
print(guests[0], invite)
print(guests[1].title(), invite)
print(guests[2].title(), invite)
print(guests[3], invite)
print(guests[4].title(), invite)
print(guests[5], invite)
print(guests[6], invite)
len(guests)
